apps/accounts/urls.py
from django.urls import path
from apps.accounts.views import register, search_users, logout_user
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search_users, name='search_users'),
]

apps/galleries/urls.py
from django.urls import path

from .views import profile, create_gallery, create_picture, picture_detail

app_name = 'galleries'

urlpatterns = [
    path('profile/', profile, name='my_profile'),
    path('profile/<str:username>/', profile, name='profile'),
    path('create-gallery/', create_gallery, name='create_gallery'),
    path('create-picture/', create_picture, name='create_picture'),
    path('pictures/<int:id>/', picture_detail, name='picture'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.galleries.urls')),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/galleries/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Gallery(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='galleries',
        null=False,
        blank=False,
    )
    name = models.CharField(
        max_length=50,
        null=False,
        blank=False,
    )
    icon = models.CharField(
        max_length=50,
        null=False,
        blank=False,
    )

    class Meta:
        unique_together = ('user', 'name')

    def __str__(self):
        return self.name


class Picture(models.Model):
    id = models.AutoField(
        primary_key=True
    )
    gallery = models.ForeignKey(
        Gallery,
        on_delete=models.CASCADE,
        related_name='pictures',
        null=False,
        blank=False,
    )
    name = models.CharField(
        max_length=50,
        null=False,
        blank=False,
    )
    description = models.TextField(
        null=False,
        blank=False,
    )
    image = models.ImageField(
        upload_to='pictures/',
        null=False,
        blank=False,
    )
    is_favorite = models.BooleanField(
        default=False,
        null=False,
        blank=False,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False
    )

    class Meta:
        unique_together = ('gallery', 'name')

    def __str__(self):
        return self.name

apps/galleries/forms.py
from django import forms
from .models import Gallery, Picture


class GalleryForm(forms.ModelForm):
    class Meta:
        model = Gallery
        fields = ['user', 'name', 'icon']
        widgets = {
            'user': forms.HiddenInput(attrs={'required': False}),
            'name': forms.TextInput(attrs={'placeholder': 'Enter Name'}),
            'icon': forms.TextInput(attrs={'placeholder': 'Enter Icon'})
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].initial = user


class PictureForm(forms.ModelForm):
    class Meta:
        model = Picture
        fields = ['gallery', 'name', 'description', 'image', 'is_favorite']
        widgets = {
            'gallery': forms.Select(attrs={'placeholder': 'Select Gallery'}),
            'name': forms.TextInput(attrs={'placeholder': 'Enter Name'}),
            'description': forms.Textarea(attrs={'placeholder': 'Enter Description'}),
        }

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['gallery'].queryset = Gallery.objects.filter(user=user)

apps/galleries/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect

from .forms import GalleryForm, PictureForm
from .models import Gallery, Picture

User = get_user_model()


@login_required
def profile(request, username=None):
    if not username:
        profile_user = request.user
    else:
        profile_user = get_object_or_404(User, username=username)

    is_own_profile = (request.user == profile_user)

    if 'gallery_id' in request.GET:
        gallery_id = request.GET['gallery_id']
        gallery = get_object_or_404(Gallery, id=gallery_id)
    else:
        gallery = profile_user.galleries.first()

    pictures = None
    gallery_id = None

    if gallery:
        pictures = Picture.objects.filter(gallery=gallery.id).order_by('-is_favorite', '-created_at')
        gallery_id = gallery.id

    galleries = profile_user.galleries.all()

    context = {
        'is_own_profile': is_own_profile,
        'profile_user': profile_user,
        'selected_gallery_id': gallery_id,
        'galleries': galleries,
        'pictures': pictures,
    }

    return render(request, 'galleries/profile.html', context)


@login_required
def create_gallery(request):
    if request.method == 'POST':
        form = GalleryForm(request.user, data=request.POST)
        if form.is_valid():
            gallery = form.save(commit=False)
            gallery.user = request.user
            gallery.save()
            return redirect('galleries:my_profile')
    else:
        form = GalleryForm(user=request.user)
    return render(request, 'galleries/create_gallery.html', {'form': form})


@login_required
def create_picture(request):
    if request.method == 'POST':
        form = PictureForm(request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            picture = form.save(commit=False)
            picture.user = request.user
            picture.save()
            return redirect('galleries:my_profile')
    else:
        form = PictureForm(user=request.user)
    return render(request, 'galleries/create_picture.html', {'form': form})


@login_required
def picture_detail(request, id):
    picture = get_object_or_404(Picture, id=id)
    author = picture.gallery.user
    return render(request, 'galleries/picture_detail.html', {'picture': picture, 'author': author})

templates/galleries/create_gallery.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Gallery</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
    <form method="post" style="width: 600px">
        {% csrf_token %}
        <h3 class="formHeader">Create Gallery</h3>

        {{ form.user }}

        {{ form.name.label_tag }}
        {{ form.name }}
        {{ form.name.errors }}

        {{ form.icon.label_tag }}
        {{ form.icon }}
        {{ form.icon.errors }}

        {% if form.non_field_errors %}
            {{ form.non_field_errors }}
        {% endif %}

        <button class="blueButton" type="submit">Create</button>
    </form>
</body>
</html>

templates/galleries/create_picture.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Picture</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
<form method="post" enctype="multipart/form-data" style="width: 600px">
    {% csrf_token %}
    <h3 class="formHeader">Create Picture</h3>

    {{ form.gallery.label_tag }}
    {{ form.gallery }}
    {{ form.gallery.errors }}


    {{ form.name.label_tag }}
    {{ form.name }}
    {{ form.name.errors }}


    {{ form.description.label_tag }}
    {{ form.description }}
    {{ form.description.errors }}


    {{ form.image.label_tag }}
    {{ form.image }}
    {{ form.image.errors }}

    <div class="checkbox-container">
        {{ form.is_favorite.label_tag }}
        {{ form.is_favorite }}
    </div>
    {{ form.is_favorite.errors }}

    {% if form.non_field_errors %}
        {{ form.non_field_errors }}
    {% endif %}


    <button class="blueButton" type="submit">Create</button>
</form>
</body>
</html>

templates/galleries/picture_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Post</title>
    <link rel="stylesheet" href="{% static 'css/picture-details.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link rel="stylesheet" href="style_details.css">
</head>
<body>
<div class="card">
    <div class="top">
        <div class="userDeatils">
            <div class="profileImg">
                <img src="{{ author.avatar.url }}" alt="user" class="cover">
            </div>
            <h3>{{ author.username }}</h3>
        </div>
        <div class="dot" onclick="window.location.href='{% url 'galleries:profile' username=author.username %}';">
            <i class="fa fa-times" aria-hidden="true"></i>
        </div>
    </div>
    <h4>{{ picture.name }}</h4>
    <div class="imgBg">
        <img src="{{ picture.image.url }}" class="cover">
    </div>
    <p class="message">
        {{ picture.description }}
    </p>
</div>
</body>

</html>

templates/galleries/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
<nav class="navbar">
    <img src="{% static 'img/logo.png' %}" class="brand-img" alt="logo">
    <div class="buttons-container">
        <button onclick="window.location.href='{% url 'accounts:search_users' %}';" class="btn profile-btn">Search
        </button>
        <button onclick="window.location.href='{% url 'accounts:logout' %}';" class="btn profile-btn">Log Out</button>
    </div>
</nav>
<header>
    <div class="container">
        <div class="profile">
            <div class="profile-image">
                <img src="{% if profile_user.avatar %} {{ profile_user.avatar.url }} {% else %} {% static 'img/anonymous.jpg' %} {% endif %}"
                     alt="">
            </div>

            <h1 class="profile-user-name">{{ profile_user.username }}</h1>

            {% if is_own_profile %}
                <div class="profile-user-settings">
                    <button onclick="window.location.href='{% url 'galleries:create_picture' %}';"
                            class="btn profile-btn"
                            style="margin-right: 2rem;">Add Picture +
                    </button>
                    <button onclick="window.location.href='{% url 'galleries:create_gallery' %}';"
                            class="btn profile-btn">
                        Add Gallery +
                    </button>
                </div>
            {% endif %}
        </div>

    </div>
</header>

<div class="container">
    <div class="categories">
        {% for gallery in galleries %}
            <a class="category {% if gallery.id == selected_gallery_id %} selected {% endif %}"
               href="{% url 'galleries:profile' username=profile_user.username %}?gallery_id={{ gallery.id }}">
                <i class="material-icons">{{ gallery.icon }}</i>
                <h7>{{ gallery.name }}</h7>
            </a>
        {% endfor %}
    </div>
</div>

<main>
    <div class="container">
        <div class="gallery">
            {% for picture in pictures %}
                <div onclick="window.location.href='{% url 'galleries:picture' id=picture.id %}';" class="gallery-item"
                     tabindex="0">
                    <img src="{{ picture.image.url }}"
                         class="gallery-image" alt=""/>

                    {% if picture.is_favorite %}
                        <div class="gallery-item-type">
                            <span class="visually-hidden"></span><i style="color: yellow" class="fa fa-star"></i>
                        </div>
                    {% endif %}

                    <div class="gallery-item-info">
                        <ul>
                            <li class="gallery-item-likes">{{ picture.name }}</li>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</main>
</body>
</html>