apps/accounts/urls.py
from django.urls import path
from apps.accounts.views import register, search_users, logout_user
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', logout_user, name='logout'),
    path('search/', search_users, name='search_users'),
]

apps/galleries/urls.py
from django.urls import path

from .views import profile, create_gallery, create_picture, picture_detail

app_name = 'galleries'

urlpatterns = [
    path('profile/', profile, name='my_profile'),
    path('profile/<str:username>/', profile, name='profile'),
    path('create-gallery/', create_gallery, name='create_gallery'),
    path('create-picture/', create_picture, name='create_picture'),
    path('pictures/<int:id>/', picture_detail, name='picture'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.accounts.urls')),
    path('', include('apps.galleries.urls')),
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    avatar = models.ImageField(
        upload_to='avatars/',
        blank=False,
        null=False
    )

apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from PIL import Image

from .models import User


class CustomUserCreationForm(UserCreationForm):
    avatar = forms.ImageField(
        required=True,
        error_messages={
            'required': 'This field is required.',
        },
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'avatar')

    def clean_avatar(self):
        avatar = self.cleaned_data.get('avatar')
        if not avatar:
            raise forms.ValidationError('This field is required.')

        img = Image.open(avatar)

        width, height = img.size
        if width != height:
            raise forms.ValidationError('Avatar should be a square image.')

        return avatar

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': 'Enter Username'})
        self.fields['email'].widget.attrs.update({'placeholder': 'Enter Email Address'})
        self.fields['password1'].widget.attrs.update({'placeholder': 'Enter Password'})
        self.fields['password2'].widget.attrs.update({'placeholder': 'Enter password'})
        self.fields['avatar'].widget.attrs.update({'placeholder': 'Choose Avatar'})

apps/accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib.auth import logout

User = get_user_model()


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'accounts/register.html', {'form': form})


@login_required
def search_users(request):
    if request.method == 'GET':
        query = request.GET.get('query', '')
        users = User.objects.filter(username__icontains=query, is_staff=False)
        return render(request, 'accounts/search_users.html', {'users': users})


def logout_user(request):
    logout(request)
    return redirect('accounts:login')

templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form method="post">
        <h3 class="formHeader">Login</h3>
        {% csrf_token %}

        <label for="username">Username</label>
        <input type="text" placeholder="Enter Username" id="username" name="username">

        <label for="password">Password</label>
        <input type="password" placeholder="Enter Password" id="password" name="password">

        {% if form.errors %}
            <p>Invalid username or password</p>
        {% endif %}

        <button class="blueButton" type="submit">Log In</button>

        <a href="{% url 'accounts:register' %}" >Create a account</a>
    </form>
</body>
</html>

templates/accounts/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Sign Up</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h3 class="formHeader">Sign Up</h3>

        <label for="username">Username</label>
        {{ form.username }}
        {{ form.username.errors }}

        <label for="email">Email</label>
        {{ form.email }}
        {{ form.email.errors }}

        <label for="password1">Password</label>
        {{ form.password1 }}
        {{ form.password1.errors }}


        <label for="password2">Confirm Password</label>
        {{ form.password2 }}
        {{ form.password2.errors }}

        <label for="avatar">Avatar</label>
        {{ form.avatar }}
        {{ form.avatar.errors }}

        <button class="blueButton" type="submit">Signup</button>

        <a href="{% url 'accounts:login' %}" >I have already account</a>
    </form>
</body>
</html>

templates/accounts/search_users.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <title>Search</title>
</head>
<body>
<nav class="navbar">
    <img src="{% static 'img/logo.png' %}" class="brand-img" alt="">
    <div class="buttons-container">
        <button onclick="window.location.href='{% url 'galleries:my_profile' %}';" class="btn search-btn">My Profile</button>
        <button onclick="window.location.href='{% url 'accounts:logout' %}';" class="btn search-btn">Log Out</button>
    </div>
</nav>
<div class="container">
    <form class="search" method="GET">
        <input type="text" class="search-box" placeholder="search" name="value">
        <button type="submit" class="btn"><i class="fas fa-search"></i></button>
        <button onclick="window.location.href='{% url 'accounts:search_users' %}';" class="btn profile-btn">Search</button>
    </form>
    {% for search_user in users %}
        <div onclick="window.location.href='{% url 'galleries:profile' username=search_user.username %}';"
             class="userDeatails">
            <div class="profileImg">
                <img src="{{ search_user.avatar.url }}" alt="user" class="cover">
            </div>
            <h3>{{ search_user.username }}</h3>
        </div>
        <hr id="hr">
    {% endfor %}
</div>